# Effort Trajectory Controller
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - waist_joint
    - shoulder_joint
    - elbow_joint
    - upper_forearm_joint
    - lower_forearm_joint
    - wrist_joint
  gains: 
    waist_joint: {p: 100.0,  d: 1.0, i: 5.0}
    shoulder_joint: {p: 500.0,  d: 1.0, i: 10.0}
    elbow_joint: {p: 300.0,  d: 1.0, i: 10.0}
    upper_forearm_joint: {p: 100.0, d: 0.1, i: 3.0}
    lower_forearm_joint: {p: 100.0,  d: 0.1, i: 3.0}
    wrist_joint: {p: 100.0,  d: 0.1, i: 1.0}

# Effort Trajectory Controller
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_finger_joint
    - right_finger_joint
  gains:
    left_finger_joint: {p: 100.0,  d: 1.0, i: 0.0}
    right_finger_joint: {p: 100.0,  d: 1.0, i: 0.0}
