# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200

# Effort Controller
mobile_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - wheel0_joint
    - wheel1_joint
    - wheel2_joint