# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200

# Velocity Trajectory Controller
wheel0_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel0_joint

# Velocity Trajectory Controller
wheel1_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel1_joint

wheel2_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel2_joint