# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Effort Trajectory Controller
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - waist_joint
    - shoulder_joint
    - elbow_joint
    - upper_forearm_joint
    - lower_forearm_joint
    - wrist_joint
  gains: 
    waist_joint: {p: 100.0,  d: 1.0, i: 5.0, i_clamp: 1}
    shoulder_joint: {p: 500.0,  d: 1.0, i: 10.0}
    elbow_joint: {p: 300.0,  d: 1.0, i: 10.0}
    upper_forearm_joint: {p: 100.0, d: 0.1, i: 3.0}
    lower_forearm_joint: {p: 100.0,  d: 0.1, i: 3.0}
    wrist_joint: {p: 100.0,  d: 0.1, i: 1.0}
  
  state_publish_rate: 63
  constraints:
    goal_time: 0.2
    waist_joint:
      goal: 0.1
      trajectory: 0.2
    shoulder_joint:
      goal: 0.2
      trajectory: 0.2
    elbow_joint:
      goal: 0.2
      trajectory: 0.2
    upper_forearm_joint:
      goal: 0.2
      trajectory: 0.2
    lower_forearm_joint:
      goal: 0.2
      trajectory: 0.2
    wrist_joint:
      goal: 0.2
      trajectory: 0.2

# Effort Trajectory Controller
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_finger_joint
    - right_finger_joint
  gains:
    left_finger_joint: {p: 100.0,  d: 1.0, i: 0.0, i_clamp: 1}
    right_finger_joint: {p: 100.0,  d: 1.0, i: 0.0, i_clamp: 1}
