# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Effort Trajectory Controller
arm_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - waist_joint
    - shoulder_joint
    - elbow_joint
    - upper_forearm_joint
    - lower_forearm_joint
    - wrist_joint