# Robot namespace
robot_name: mobile_manipulator

# Odometry topic to subscribe 
#odom_topic: odometry/filtered

# Manipulator DOFs in order from waist to wrist
manipulator_dof_names: 
  - waist_joint
  - shoulder_joint
  - elbow_joint
  - upper_forearm_joint
  - lower_forearm_joint
  - wrist_joint

# Manipulator Controllers in order from waist to wrist
manipulator_controllers: 
  - waist_controller
  - shoulder_controller
  - elbow_controller
  - upper_forearm_controller
  - lower_forearm_controller
  - wrist_controller

# Parameters of controller
compensate_topdownEffects: False # True False
compensate_nonlinearInJointSpace: True
use_augmented_projections: True

# Parameter for singularity handling
# 0 -> Algorithm proposed by Khatib et al.
# 1 -> Algorithm without torque projection
# 2 -> Algorithm with non singular torque projection
singularity_handling: 1

# Parameter for joint limit avoidance
# -1 -> Not handling joint limits
#  0 -> Repulsive artificial potentials
#  1 -> Intermediate value
#  3 -> SJS
joint_limit_avoidance: 1