robot_name: mobile_manipulator
odom_topic: odometry/filtered
manipulator_dof_names: 
  - waist_joint
  - shoulder_joint
  - elbow_joint
  - upper_forearm_joint
  - lower_forearm_joint
  - wrist_joint
manipulator_controllers: 
  - waist_controller
  - shoulder_controller
  - elbow_controller
  - upper_forearm_controller
  - lower_forearm_controller
  - wrist_controller